# sapphone !!! :3
# strings that use escapes (\) should be contained in 'single quotation marks'

# SAPPHONE MINECRAFT GUIDE
# target_pattern: '^.*<username> (.*)'
# If your username begins with a "." you MUST have a "\" to the right of the "<"
# Your target_file should point to the "logs/latest.log" in your Minecraft directory.
# DO NOT open sapphone before Minecraft. You MUST open Minecraft to the title screen before starting sapphone.

# file sapphone reads from
target_file: '/home/gelvetica/PycharmProjects/sapphone/test.txt'
# regex pattern for detecting message, the content of the first group will be read aloud
target_pattern: '(.*)'
# how often sapphone should check the target file for changes
refresh_rate: 0.1
tts:
  # disabling does not do anything currently
  enabled: true
  # specify which engine to use
  engine: google-tts
  engines:
    # engine: engine config
    sapi:
      voice:
        # The available voices will be different for each system
        # You can view a list of available voices by running sapphone with this field left blank.
        voice: 'Microsoft David Desktop'
        rate: 0
    dectalk:
      advanced:
        # Refer to the DECTalk in-line commands manual for options on customizing the voice.
        # https://dectalk.github.io/dectalk/idh_ref_1_dectalk_software_in_line_commands_overview.htm
        # These should go in your prefix.
        prefix: "[:phone on]"
        suffix: ""
      engine:
        path_to_executable: '/home/gelvetica/dectalk/say'
    modern-sam:
      voice:
        speed: 72
        pitch: 64
        mouth: 128
        throat: 128
      pronunciation:
        phonetic: false
        sing: false
        moderncmu: true
      engine:
        path_to_executable: '/home/gelvetica/SAM/sam-linux'
    google-tts:
      # See gTTS manual for guides on changing the accent https://gtts.readthedocs.io/en/stable/module.html#localized-accents
      # you can be british !!!!
      voice:
        lang: en
        tld: com
        slow: False
# Substitute words in the message before reading aloud
basic_substitutions:
  # target: replacement
  dr: doctor
  bc: because
# run re.sub on message before reading aloud
regex_substitutions:
  # pattern: string
  '\B:3\b': meow
